name: CI pipeline

on:
  push: # No branch filtering - will run on all branches
  pull_request:

jobs:
  ci:
    name: CI pipeline
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: petclinic

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make wrapper executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'